
version: "3"

services:
  redis:
    image: 'redis:5-alpine'
    command: redis-server --appendonly yes
    volumes:
      - .data/redis:/data
    security_opt:
      - apparmor:unconfined
    ports:
      - 6379
    networks:
      - app

  db:
    image: mysql:8.0.21
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - .data/dbdata/:/var/lib/mysql/
    ports:
      - "32776:3306"
    networks:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE: bhcosta90/php:8.0-dev
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app

  cron:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE: bhcosta90/php:8.0.cron
    restart: always
    volumes:
      - ./:/var/www/html
    networks:
      - app

networks:
  app:
    driver: bridge
